'use client';
import { useEffect, useMemo, useState } from 'react';
import AppShell from '@/components/AppShell';
import AuthGate from '@/components/AuthGate';
import GlassCard from '@/components/GlassCard';
import { api } from '@/lib/api';
import { Crown, Download, FileSpreadsheet, FolderKanban, Plus, Save, Upload, UsersRound } from 'lucide-react';

type User={user_id:string;nim:string;name:string;role:string};
type Group={group_id?:string;project_code:string;name:string;meeting_no?:number;topic?:string;member_ids:string[];leader_id?:string};
type ImportReport={project_code:string;groups:number;members:number;warnings?:string[]};
const SETS=[
  ['STUDENT_LED','Pembelajaran Dipandu Mahasiswa','2 mahasiswa'],
  ['UTS_BLUEPRINT','UTS Curriculum Blueprint','4–5 mahasiswa'],
  ['UAS_CURRICULUM','UAS Final Curriculum','4–5 mahasiswa']
] as const;
const validCount=(code:string,n:number)=>code==='STUDENT_LED'?n===2:n>=4&&n<=5;
const countLabel=(code:string)=>code==='STUDENT_LED'?'2':'4–5';
const empty=(code='STUDENT_LED'):Group=>({project_code:code,name:'',meeting_no:code==='STUDENT_LED'?3:undefined,topic:'',member_ids:[],leader_id:''});

export default function AdminGroups(){
  const[groups,setGroups]=useState<Group[]>([]);const[users,setUsers]=useState<User[]>([]);const[code,setCode]=useState('STUDENT_LED');const[g,setG]=useState<Group>(empty());const[msg,setMsg]=useState('');const[importBusy,setImportBusy]=useState(false);const[report,setReport]=useState<ImportReport|null>(null);
  const load=async()=>{const[a,b]=await Promise.all([api<Group[]>('adminListGroups'),api<User[]>('adminListUsers')]);setGroups(a);setUsers(b.filter(u=>u.role==='mahasiswa'))};
  useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
  const rows=useMemo(()=>groups.filter(x=>x.project_code===code),[groups,code]);
  const assigned=useMemo(()=>{const m=new Map<string,string>();rows.forEach(x=>{if(x.group_id!==g.group_id)x.member_ids.forEach(id=>m.set(id,x.name))});return m},[rows,g.group_id]);
  const select=(c:string)=>{setCode(c);setG(empty(c));setMsg('');setReport(null)};
  const toggle=(id:string)=>setG(x=>{const selected=x.member_ids.includes(id);if(!selected&&code!=='STUDENT_LED'&&x.member_ids.length>=5)return x;if(!selected&&code==='STUDENT_LED'&&x.member_ids.length>=2)return x;const member_ids=selected?x.member_ids.filter(v=>v!==id):[...x.member_ids,id];let leader_id=x.leader_id||'';if(selected&&leader_id===id)leader_id='';if(!selected&&!leader_id)leader_id=id;return {...x,member_ids,leader_id}});
  const save=async()=>{try{if(!validCount(code,g.member_ids.length))throw new Error(`Kelompok ${code} harus berisi ${countLabel(code)} mahasiswa.`);if(!g.leader_id)throw new Error('Pilih ketua kelompok.');const d=await api<{group:Group}>('adminSaveGroup',{group:g});setG(d.group);setMsg('Kelompok tersimpan.');await load()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
  const importExcel=async(file:File|null)=>{if(!file)return;setImportBusy(true);setMsg('');setReport(null);try{const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const ws=wb.Sheets['KELOMPOK']||wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('Sheet KELOMPOK tidak ditemukan.');const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:'',raw:false});const normalized=raw.map(r=>{const low:Record<string,unknown>={};Object.keys(r).forEach(k=>low[k.trim().toLowerCase()]=r[k]);return {group_name:String(low.group_name??low.kelompok??low.nama_kelompok??'').trim(),nim:String(low.nim??'').trim(),role:String(low.role??'MEMBER').trim().toUpperCase()}}).filter(r=>r.group_name||r.nim);if(!normalized.length)throw new Error('Tidak ada baris kelompok yang terbaca.');const result=await api<ImportReport>('adminImportGroups',{project_code:code,rows:normalized});setReport(result);setMsg(`Import selesai: ${result.groups} kelompok, ${result.members} anggota.`);await load()}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setImportBusy(false)}};
  return <AuthGate adminOnly><AppShell title="Kelompok"><div className="stack">
    <GlassCard><div className="row between wrap gap"><div><span className="eyebrow">3 GROUP SET</span><h2>Kelompok Pembelajaran</h2><p className="muted">Pembelajaran Dipandu Mahasiswa = tepat 2 mahasiswa; UTS/UAS = 4–5 mahasiswa. Kelompok UTS dan UAS boleh sama atau berbeda.</p></div><UsersRound size={32}/></div><div className="project-tabs">{SETS.map(([c,label,size])=><button key={c} className={code===c?'project-tab active':'project-tab'} onClick={()=>select(c)}><FolderKanban/>{label}<small>{size}</small></button>)}</div></GlassCard>
    <GlassCard><div className="row between wrap gap"><div><span className="eyebrow">IMPORT KELOMPOK</span><h3>Excel Group Assignment</h3><p className="muted">Gunakan template dengan kolom <strong>group_name</strong>, <strong>nim</strong>, dan <strong>role</strong> (LEADER/MEMBER). Import berlaku untuk group set yang sedang aktif.</p></div><div className="row wrap gap"><a className="button soft" href="/templates/import-groups.xlsx" download><Download/>Template Excel</a><label className="button primary file-button"><Upload/>{importBusy?'Mengimpor...':'Import Excel'}<input hidden disabled={importBusy} type="file" accept=".xlsx,.xls" onChange={e=>{importExcel(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label></div></div>{report&&<div className="notice"><FileSpreadsheet size={17}/><strong>{report.groups} kelompok</strong> dan {report.members} anggota berhasil diimpor.{(report.warnings||[]).map((w,i)=><span key={i}> {w}</span>)}</div>}</GlassCard>
    <div className="admin-split"><GlassCard className="admin-list"><div className="row between"><div><span className="eyebrow">{code}</span><h3>{rows.length} Kelompok</h3></div><button className="icon-button" onClick={()=>setG(empty(code))}><Plus/></button></div><div className="scroll-list">{rows.map(x=><button key={x.group_id} className={g.group_id===x.group_id?'select-row active':'select-row'} onClick={()=>setG({...x,leader_id:x.leader_id||x.member_ids[0]||''})}><strong>{x.name}</strong><small>{x.member_ids.length} anggota{x.meeting_no?` • Pertemuan ${x.meeting_no}`:''}</small></button>)}</div></GlassCard>
      <GlassCard><div className="form-grid two"><label className="field"><span>Nama kelompok</span><input value={g.name} onChange={e=>setG({...g,name:e.target.value})} placeholder="Contoh: Blueprint 1"/></label><label className="field"><span>Group set</span><input value={code} disabled/></label>{code==='STUDENT_LED'&&<label className="field"><span>Pertemuan</span><select value={g.meeting_no||3} onChange={e=>setG({...g,meeting_no:Number(e.target.value)})}>{[3,4,9,10,11,12,13].map(n=><option value={n} key={n}>Pertemuan {n}</option>)}</select></label>}<label className="field"><span>Topik / tema</span><input value={g.topic||''} onChange={e=>setG({...g,topic:e.target.value})} placeholder={code==='STUDENT_LED'?'Topik sesi':'Tema kurikulum pelatihan'}/></label></div><div className="field"><span>Anggota — {countLabel(code)} mahasiswa</span><div className="member-grid">{users.map(u=>{const other=assigned.get(u.user_id),selected=g.member_ids.includes(u.user_id);return <button type="button" disabled={!!other&&!selected} key={u.user_id} className={selected?'member-chip selected':'member-chip'} onClick={()=>toggle(u.user_id)}><span className="avatar small">{u.name[0]}</span><span className="grow"><strong>{u.name}</strong><small>{u.nim}{other?` • ${other}`:''}</small></span>{g.leader_id===u.user_id&&<Crown className="leader-crown"/>}</button>})}</div></div>{g.member_ids.length>0&&<label className="field"><span>Ketua</span><select value={g.leader_id||''} onChange={e=>setG({...g,leader_id:e.target.value})}><option value="">Pilih ketua</option>{g.member_ids.map(uid=>{const u=users.find(x=>x.user_id===uid);return <option value={uid} key={uid}>{u?.name} — {u?.nim}</option>})}</select></label>}<div className="right-actions"><span className={`badge ${validCount(code,g.member_ids.length)?'success':''}`}>{g.member_ids.length} / {countLabel(code)} mahasiswa</span><button className="button primary" onClick={save}><Save/>Simpan Kelompok</button></div></GlassCard></div>
    {msg&&<div className="notice selectable">{msg}</div>}
  </div></AppShell></AuthGate>;
}
